# Generated by Django 5.1.5 on 2025-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_product_weather_tag_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
