# Generated by Django 5.1.5 on 2025-01-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
